### ISSUE TITLE
Letting go of ctrl will always result in snap to grid enabling

### ISSUE THREAD

**Issue by jukibom** [CircuitLord/NotReaper#16]
Holding and letting go of CTRL re-enables the grid if you're mapping with it disabled. This is probably due to the toolbar behaviour being selected and enabling the grid if its behaviour defaults to it.

**Comment by Mettra** [comment]
@CircuitLord So this is because the drag tool gets reverted once ctrl is no longer being held down, and the previous tool gets re-selected, which sets the snapping mode. But the same thing also happens when in no grid mode and you select any other note.

Do we want selecting notes to always take you to grid mode? Or should we change it so that selecting a note keeps is in the snap mode you're currently in? (With probably some special case from going in/out of melee)

**Comment by CircuitLord** [comment]
Forgot that I fixed this a long time ago :D
